theme: jekyll-theme-cayman
title: Improve Your Code Review Game
author:
  name: Coleen Ho
analytics:
  provider: "google-gtag"
  google:
    measurement_id: G-79TW0SLZ9L
    anonymize_ip: # true, false (default)
